# Generated by Django 3.2.23 on 2025-09-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_callrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='printorder',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Обработано'),
        ),
    ]
