# Generated by Django 3.2.23 on 2025-09-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_printorder_is_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('3d_printing', '3D печать'), ('engineering', 'Инжиниринг'), ('reverse_engineering', 'Реверс-инжиниринг'), ('3d_scanning', '3D сканирование'), ('3d_modeling', '3D моделирование'), ('post_processing', 'Постобработка')], max_length=20, verbose_name='Тип услуги')),
                ('image', models.ImageField(upload_to='services/', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Изображение услуги',
                'verbose_name_plural': 'Изображения услуг',
                'ordering': ['service_type', 'order'],
            },
        ),
    ]
