# Generated by Django 3.2.23 on 2025-09-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_serviceimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('vk', 'VKontakte'), ('youtube', 'YouTube')], max_length=20, unique=True, verbose_name='Социальная сеть')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Социальная ссылка',
                'verbose_name_plural': 'Социальные ссылки',
                'ordering': ['order'],
            },
        ),
    ]
