# Generated by Django 3.2.23 on 2025-09-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_sociallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+7 (929) 178-20-00', max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(default='modelix.stl@gmail.com', max_length=254, verbose_name='Email')),
                ('work_hours', models.CharField(default='ПН-ПТ 10:00-20:00', max_length=50, verbose_name='Часы работы')),
                ('owner_name', models.CharField(default='Худолей Илья Константинович', max_length=100, verbose_name='ФИО владельца')),
                ('inn', models.CharField(default='780618190040', max_length=20, verbose_name='ИНН')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
            },
        ),
    ]
