# Generated by Django 3.2.23 on 2025-09-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('3d_modeling', '3D моделирование'), ('3d_printing', '3D печать'), ('3d_scanning', '3D сканирование'), ('engineering', 'Инжиниринг')], max_length=20, unique=True, verbose_name='Тип услуги')),
                ('title', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('description', models.TextField(verbose_name='Описание услуги')),
                ('image', models.ImageField(upload_to='services/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги (Наши 3D-возможности)',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='ServiceImage',
        ),
    ]
