# Generated by Django 3.2.23 on 2025-09-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20250913_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('3d_modeling', '3D моделирование'), ('3d_printing', '3D печать'), ('3d_scanning', '3D сканирование'), ('reverse_engineering', 'Реверс-инжиниринг'), ('engineering', 'Инжиниринг'), ('post_processing', 'Постобработка')], max_length=20, unique=True, verbose_name='Тип услуги'),
        ),
    ]
