# Generated by Django 3.2.23 on 2025-09-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_service_service_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Главное изображение', max_length=100, verbose_name='Название')),
                ('image', models.ImageField(default='hero/hero_block1.png', upload_to='hero/', verbose_name='Изображение')),
                ('alt_text', models.CharField(default='3D принтер', max_length=200, verbose_name='Альтернативный текст')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Изображение Hero блока',
                'verbose_name_plural': 'Изображения Hero блока',
            },
        ),
    ]
