# Generated by Django 3.2.23 on 2025-09-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_heroimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroimage',
            options={'verbose_name': 'Изображение первого блока', 'verbose_name_plural': 'Изображения первого блока'},
        ),
        migrations.AlterField(
            model_name='heroimage',
            name='image',
            field=models.ImageField(default='hero/hero_block.png', upload_to='hero/', verbose_name='Изображение'),
        ),
    ]
