# Generated by Django 3.2.23 on 2025-09-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20250916_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroimage',
            name='image',
            field=models.ImageField(default='hero/hero_block1.png', upload_to='hero/', verbose_name='Изображение'),
        ),
    ]
