# Generated by Django 3.2.23 on 2025-09-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_heroimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='owner_name',
            field=models.CharField(default='ИП Худолей Илья Константинович', max_length=100, verbose_name='ФИО владельца'),
        ),
    ]
