# Generated by Django 3.2.25 on 2025-11-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_update_owner_name_with_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_type', models.CharField(choices=[('experience', 'Опыт работы'), ('orders', 'Выполненные заказы'), ('technologies', 'Технологии печати')], max_length=20, unique=True, verbose_name='Тип статистики')),
                ('number', models.CharField(default='3+', max_length=20, verbose_name='Число')),
                ('label', models.CharField(max_length=100, verbose_name='Подпись')),
                ('icon_class', models.CharField(choices=[('fa-calendar-alt', 'Календарь'), ('fa-check-circle', 'Галочка'), ('fa-cube', 'Куб')], default='fa-calendar-alt', max_length=50, verbose_name='CSS класс иконки')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('vk', 'VKontakte'), ('youtube', 'YouTube')], max_length=20, unique=True, verbose_name='Социальная сеть'),
        ),
    ]
