# Generated by Django 3.2.25 on 2025-11-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20251105_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='printorder',
            name='service_type',
            field=models.CharField(blank=True, choices=[('other', 'Другое'), ('complex', 'Комплекс услуг'), ('3d_modeling', '3D моделирование'), ('3d_printing', '3D печать'), ('3d_scanning', '3D сканирование'), ('reverse_engineering', 'Реверс-инжиниринг'), ('engineering', 'Инжиниринг'), ('post_processing', 'Постобработка')], default='other', max_length=30, verbose_name='Тип услуги'),
        ),
    ]
