# Generated by Django 3.2.25 on 2025-11-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_printorder_service_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('vk', 'ВКонтакте (группа)'), ('telegram', 'Telegram'), ('telegram_channel', 'Telegram канал'), ('youtube', 'YouTube'), ('ozon', 'Озон'), ('avito', 'Авито')], max_length=20, unique=True, verbose_name='Платформа')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Ссылка на маркетплейс',
                'verbose_name_plural': 'Ссылки на маркетплейсы',
                'ordering': ['order'],
            },
        ),
    ]
