# Generated by Django 3.2.25 on 2025-11-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_marketplacelink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortfolioItem',
        ),
        migrations.AlterModelOptions(
            name='marketplacelink',
            options={'ordering': ['order'], 'verbose_name': 'Ссылка на маркетплейс/соц сеть', 'verbose_name_plural': 'Маркетплейсы и соц сети'},
        ),
        migrations.AlterField(
            model_name='marketplacelink',
            name='description',
            field=models.TextField(blank=True, max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='marketplacelink',
            name='platform',
            field=models.CharField(choices=[('vk_group', 'Группа ВКонтакте'), ('telegram', 'Telegram'), ('youtube', 'YouTube'), ('ozon', 'Озон'), ('avito', 'Авито'), ('telegram_channel', 'Telegram канал')], max_length=20, unique=True, verbose_name='Платформа'),
        ),
        migrations.AlterField(
            model_name='marketplacelink',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
