# Generated by Django 3.2.25 on 2025-11-05 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20251105_2230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
    ]
