# Generated by Django 3.2.25 on 2025-11-05 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_service_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TechnologyPrice',
        ),
    ]
