# Generated by Django 3.2.25 on 2025-11-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_technology_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorksBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_screenshot', models.ImageField(blank=True, help_text='Скриншот с видосами из YouTube', null=True, upload_to='works/', verbose_name='Скриншот YouTube')),
                ('youtube_url', models.URLField(blank=True, default='', help_text='Ссылка на YouTube канал или плейлист', verbose_name='Ссылка на YouTube')),
                ('bottom_text', models.TextField(default='Ознакомьтесь с нашими работами в соц сетях и на маркетплейсах', max_length=200, verbose_name='Текст внизу')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Блок "Наши работы"',
                'verbose_name_plural': 'Блок "Наши работы"',
            },
        ),
    ]
