# Generated by Django 3.2.25 on 2025-11-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_worksblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_text', models.TextField(default='Вы можете следить за нашими проектами в социальных сетях', max_length=200, verbose_name='Текст о соцсетях')),
                ('marketplace_text', models.TextField(default='Мы выпускаем готовую продукцию. Отзывы, готовую продукцию и многое другое вы можете посмотреть на наших площадках', max_length=300, verbose_name='Текст о продукции')),
                ('social_banner_text', models.TextField(default='Вы можете смотреть нас в социальных сетях', max_length=150, verbose_name='Текст плашки соцсетей')),
                ('main_screenshot', models.ImageField(blank=True, help_text='Скриншот, который отображается по умолчанию', null=True, upload_to='projects/', verbose_name='Главный скриншот')),
                ('main_url', models.URLField(blank=True, default='', help_text='Ссылка при клике на главный скриншот', verbose_name='Главная ссылка')),
                ('left_screenshot', models.ImageField(blank=True, help_text='Скриншот в левом окне', null=True, upload_to='projects/', verbose_name='Левый скриншот')),
                ('left_url', models.URLField(blank=True, default='', help_text='Ссылка при клике на левый скриншот', verbose_name='Левая ссылка')),
                ('right_screenshot', models.ImageField(blank=True, help_text='Скриншот в правом окне', null=True, upload_to='projects/', verbose_name='Правый скриншот')),
                ('right_url', models.URLField(blank=True, default='', help_text='Ссылка при клике на правый скриншот', verbose_name='Правая ссылка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Блок "НАШИ ПРОЕКТЫ"',
                'verbose_name_plural': 'Блок "НАШИ ПРОЕКТЫ"',
            },
        ),
        migrations.AlterModelOptions(
            name='worksblock',
            options={'verbose_name': 'Блок "Наши работы" (старый)', 'verbose_name_plural': 'Блок "Наши работы" (старый)'},
        ),
    ]
