# Generated by Django 3.2.25 on 2025-11-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20251106_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsblock',
            name='intro_text',
            field=models.TextField(default='Отслеживайте наши проекты в социальных сетях', max_length=200, verbose_name='Текст о соцсетях'),
        ),
    ]
