# Generated by Django 3.2.23 on 2025-11-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_projectsblock_intro_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplacelink',
            name='platform',
            field=models.CharField(choices=[('vk_group', 'Группа ВКонтакте'), ('telegram', 'Telegram'), ('youtube', 'YouTube'), ('ozon', 'Озон'), ('avito', 'Авито')], max_length=20, unique=True, verbose_name='Платформа'),
        ),
        migrations.AlterField(
            model_name='projectsblock',
            name='intro_text',
            field=models.TextField(default='С примерами проектов и тем, как мы их реализуем, можно ознакомиться в наших соцсетях.', max_length=200, verbose_name='Текст о соцсетях'),
        ),
    ]
