# Generated by Django 3.2.23 on 2025-11-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_update_projects_intro_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsblock',
            name='marketplace_text',
            field=models.TextField(default='Также, Помимо индивидуальных проектов, мы выпускаем готовую продукцию; оценить её качество и прочитать отзывы можно на наших онлайн-витринах.', max_length=300, verbose_name='Текст о продукции'),
        ),
    ]
