# Generated by Django 3.2.23 on 2025-11-18 19:11

from django.db import migrations, models


def update_marketplace_text_lowercase(apps, schema_editor):
    ProjectsBlock = apps.get_model('main', 'ProjectsBlock')
    ProjectsBlock.objects.filter(
        marketplace_text__contains='Помимо'
    ).update(
        marketplace_text='Также, помимо индивидуальных проектов, мы выпускаем готовую продукцию; оценить её качество и прочитать отзывы можно на наших онлайн-витринах.'
    )


def reverse_update_marketplace_text_lowercase(apps, schema_editor):
    ProjectsBlock = apps.get_model('main', 'ProjectsBlock')
    ProjectsBlock.objects.filter(
        marketplace_text__contains='помимо'
    ).update(
        marketplace_text='Также, Помимо индивидуальных проектов, мы выпускаем готовую продукцию; оценить её качество и прочитать отзывы можно на наших онлайн-витринах.'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_update_marketplace_text_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsblock',
            name='marketplace_text',
            field=models.TextField(default='Также, помимо индивидуальных проектов, мы выпускаем готовую продукцию; оценить её качество и прочитать отзывы можно на наших онлайн-витринах.', max_length=300, verbose_name='Текст о продукции'),
        ),
        migrations.RunPython(update_marketplace_text_lowercase, reverse_update_marketplace_text_lowercase),
    ]
