# Generated by Django 3.2.23 on 2025-11-22 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_update_marketplace_text_lowercase'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='orders/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='main.printorder', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Файл заявки',
                'verbose_name_plural': 'Файлы заявок',
                'ordering': ['-created_at'],
            },
        ),
    ]
