# Generated by Django 3.2.23 on 2026-05-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_orderfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplacelink',
            name='platform',
            field=models.CharField(choices=[('vk_group', 'Группа ВКонтакте'), ('telegram', 'Telegram'), ('youtube', 'YouTube'), ('ozon', 'Озон'), ('avito', 'Авито'), ('wildberries', 'Wildberries')], max_length=20, unique=True, verbose_name='Платформа'),
        ),
    ]
